[package]
name = "exo_utils"
version = "1.0.0"
edition = "2021"

[dependencies]
bitflags = "2"
colorgrad = "0.6.2"
exo_var = { path = "../exo-var" }
lazy_static = "1.4.0"
modular-bitfield = "0.11.2"
nnsdk = { git = "https://github.com/ultimate-research/nnsdk-rs" }
once_cell = "1.15.0"
parking_lot = "0.11.2"
skyline = { git = "https://github.com/ultimate-research/skyline-rs" }
skyline_smash = { git = "https://github.com/blu-dev/skyline-smash.git", features = ["weak_l2cvalue"] }
smash_script = { git = "https://github.com/blu-dev/smash-script.git", branch = "development" }
smash_singletons = { git = "https://github.com/WuBoytH/smash_singletons.git" }
smashline = { git = "https://github.com/HDR-Development/smashline" }
smash2 = { package = "smash", git = "https://github.com/blu-dev/smash-rs" }